name: Generate Snake Animation

on:
  schedule:
    # Runs every day at midnight UTC
    - cron: "0 0 * * *"
  workflow_dispatch: # Allows manual trigger

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Generate the snake
      - uses: Platane/snk@v3
        with:
          github_user_name: anburocky3
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      # Push the generated files to the output branch
      - name: Push generated files to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
